# -*- encoding: utf-8 -*-
require "yaml"
require "xenapi/session"
require "xenapi/error"
require "xenapi/virtual_machine"
require "xenapi/storage"
require "xenapi/vdi"
require "xenapi/vdb"
require "xenapi/task"
require "xenapi/hypervisor_connection"
